#!/bin/sh

if [ "$1" = "-f" ]; then
  shift
  files=`cat $1`
else
  files=$*
fi

# use the location of this script to setup paths if needed
if [ "$SLIDEDIR" = "" ]; then
	[ "$PROJDIR" = "" ] && PROJDIR="`dirname $0`/../.."
	SLIDEDIR="$PROJDIR/LCA2019/slides"
fi

#if [ -d $SLIDEDIR ]; then
#	cd $SLIDEDIR || exit 2
#fi
#      {printf "incode: %d, inaside: %d inslide: %d\n", incode, inaside, inslide}
slidefiles=""
for i in $files; do
	f="$i"
	[ ! -f "$i" ] && f="$SLIDEDIR/`basename $i`"
	if [ ! -f "$f" ]; then 
		echo "cannot find '$i' or '$f'"
		exit 1;
	fi
	slidefiles="$slidefiles $f"
done

cat $slidefiles \
	| egrep -v '^#.*' \
	| tr '\t' '`' \
	| awk -F\` '
      BEGIN { printf "<div class=\"slides\">\n"; 
	  			inslide = 0; incode = 0; inaside = 0; slideNum = 0;
			}
			$1 != "" && incode == 0 { 
					if (inlist==1) {inlist = 0; printf "\t</ul>\n" }
					if (inaside>0) {printf "\t</aside>\n"; inaside = 0; }
					if (inslide==1) printf "</section>\n";
					slidenum = slidenum+1
					if (slidenum == 1) { 
						printf("<section style=\"text-align: left;\"  data-state=\"title-slide\" data-background-image=\"css/theme/lca2019-title-bg-transparent.svg\">\n\t<h2>%s</h2>\n",$1); 
					}
					else {
						printf "<section class=\"lca-slide\"  data-state=\"normal-slide\" >\n\t<h2>%s</h2>\n",$1; 
					}
					inslide=1
			}
			$0 == "" && incode == 0 { 
					if (inslide == 1) {
							printf("<br/>\n")
					} else { 
						print
					}
			}
			$0 != "" && $1 == "" && incode == 0 {
			    if (substr($2,1,2) != "--" && substr($2,1,3) != "###") {
					if (inaside > 0) {
						printf("</aside>\n")
						inaside = 0;
					}
					if ($2=="") {
						if (inlist == 0) {
							inlist = 1
							printf "\t<ul>\n\t<li>%s</li>\n\t\n",$0; 
						} else {
							printf "\t<li>%s</li>\n\t\n",$0; 
						}
					}
					else {
						if (inlist==1) {inlist = 0; printf "\t</ul>\n" }
						printf "\t<p>\n\t%s\n\t</p>\n",$2; 
					}
				} else if (substr($2,1,3) == "###") {
					if (inlist==1) {inlist = 0; printf "\t</ul>\n" }
					incode = 1; 
					printf("<div %s><pre><code>", substr($2, 3, length($2)));
					$2 = ""
				} else {
					if (inaside==0) printf "\t<aside class=\"notes\">\n"
					printf "\t\t%s\n",substr($2,3,10000); 
					inaside=NR
				}
			}
			incode == 1 {
					if ($1 == "" && $2 == "###") { incode = 0; printf("</code></pre></div>\n"); }
					else { print substr($0,2,length($0)) }
			}
			END {printf("</section>\n</div>\n")}
    ' \
	| tr '`' '\t'
