#!/bin/bash
#
#  insert a file between markers in another file

START_MARK=' include user data between here... '
END_MARK=' ... and here '

if [ ! -r "$1" ]; then
  echo usage: `basename $0` master-file [ snippet-file ]
  exit 2
fi 

master="$1"
snippet=$2

if [ ! -f "$master" ]; then
	echo "can't file master file $master"
	exit 1
fi
if [ ! -f "$snippet" ]; then
	echo "can't file snippet file $snippet"
	exit 1
fi

cp "$master" "$master".bak || exit 3

cat "$master" | awk -v marker="$START_MARK" '
	seen != 1 {print}
  $0 ~ marker {seen = 1}
' > "$master".new || exit 4

cat $snippet >> "$master".new || exit 5

cat "$master" | awk -v marker="$END_MARK" '
  $0 ~ marker {seen = 1}
	seen >= 1{print}
' >> "$master".new

mv "$master".new "$master"
